### ISSUE TITLE
[Enhancement] events UI redesign

### ISSUE THREAD

**Issue by infinity1729** [infinity1729/EventListing#10]
**Description**
Redesign the UI of listed events

**current UI**
![image](https://user-images.githubusercontent.com/52048907/205686302-c6175ddf-be24-43b8-87c6-710d777b826f.png)

**expected UI**
![image](https://user-images.githubusercontent.com/52048907/205687086-49009c75-4796-43f1-8423-5a321e90468d.png)

**Comment by jatin00000** [comment]
Hey! I want to work on this issue. Can you assign it to me?

**Comment by infinity1729** [comment]
Sure! Do let us know if any further clarifications needed.

**Comment by jatin00000** [comment]
Issue Solved!.
Please merge the Pull request.

**Comment by infinity1729** [comment]
> Issue Solved!. Please merge the Pull request.

Merged! Thanks for contibuting. 🚀
Might have a look at new issues :)
