### ISSUE TITLE
[New Feature] Backend: add new model of users

### ISSUE THREAD

**Issue by infinity1729** [infinity1729/EventListing#15]
**Description**
Create a new model of user having following fields
- Username
- Name
- Email
- Roll Number
- Department
- Date joined
- Profile Image (optional)

**Comment by infinity1729** [comment]
to discuss more about the fields head over to the codepeak discord server

**Comment by ghost** [comment]
assign this to me

**Comment by infinity1729** [comment]
Just to add on, current models are located in `backend/events/models.py`

**Comment by infinity1729** [comment]
@itz-deepak any updates?

**Comment by pundarikaksha7** [comment]
Kindly assign

**Comment by ghost** [comment]
@infinity1729 Will be completed by today, facing some system error while using python 3.7

**Comment by infinity1729** [comment]
Sure! we can discuss in the discord server if you need any help with the errors.

@pundarikaksha7 sorry this issue is currenlty assigned to itz-deepak, would love to have you for other unassigned backend issues. 🙌

**Comment by ghost** [comment]
Please review my PR @infinity1729

**Comment by infinity1729** [comment]
I am sorry for the delay, I got involved with some other tasks 😔.
Have given a quick review to the code and it looks fine to me. Will try to test it asap.
