### ISSUE TITLE
[Enhancement] Frontend: display venue from the fetched API

### ISSUE THREAD

**Issue by infinity1729** [infinity1729/EventListing#17]
**Description**
As you can see in Image 2 that in API call, venue is being passed into the API, but as shown in image 1 it is currently not displayed. 
Expected result is to display as `Venue:{fetched venue}`.

Currently api is fetched in `frontend/src/components/ClubList.jsx`. and the response object is stored in `Elist`.

**Screenshot**
Image 1
![image](https://user-images.githubusercontent.com/52048907/207422746-aaa3590b-6cac-4421-afa6-d4f0b3012955.png)

Image 2
![image](https://user-images.githubusercontent.com/52048907/207422952-e7192457-8313-4210-acdd-ef11e802cadb.png)

**Comment by pranavjainjs** [comment]
I'd like to work on this issue.

**Comment by infinity1729** [comment]
Sure! Do let us know if any help needed.
