### ISSUE TITLE
[Enhancement] Add border shadow to login/signup card in "restructure-frontend" branch

### ISSUE THREAD

**Issue by addy-1406** [infinity1729/EventListing#28]
We want the card to have a border shadow similar to this :
![image](https://user-images.githubusercontent.com/72205646/207886165-43437c80-ee2f-4dfe-9256-7c57d77d81ed.png)

code for the card can be found at :
`frontend/src/components/LoginPageCard/Card`

**Comment by itz-deepak** [comment]
@addy-1406 This LoginPageCard is not there in components

**Comment by Rishav1707** [comment]
Shall I work on this issue?? @addy-1406

**Comment by addy-1406** [comment]
@Rishav1707 I have assigned this issue to you!

**Comment by Rishav1707** [comment]
I am unable to install the backend dependencies, following errors have occurred...

![pip install](https://user-images.githubusercontent.com/97666287/208241561-5eb07ee3-58e0-404c-9d75-5307d606f513.png)

**Comment by Rishav1707** [comment]
@addy-1406 Website is showing totally different things after hosting with local host 3000.

![Screenshot 2022-12-17 180031](https://user-images.githubusercontent.com/97666287/208241997-5cd5185c-ff29-4234-aa14-e6bfcd1d88da.png)

**Comment by Rishav1707** [comment]
@addy-1406 Please tell me what to do now

**Comment by addy-1406** [comment]
`http://localhost:3000/userLogin` 
 
go to this url to view the userLogin Page....also make sure you have switched to 'restructure-frontend' branch.

**Comment by addy-1406** [comment]
> I am unable to install the backend dependencies, following errors have occurred...
> 
> ![pip install](https://user-images.githubusercontent.com/97666287/208241561-5eb07ee3-58e0-404c-9d75-5307d606f513.png)

https://www.alphr.com/pip-is-not-recognized-as-an-internal-or-external-command/

Please check if your python and pip are correctly installed and added to the path.
