### ISSUE TITLE
[Bug] Frontend: semicolon at the end of list of clubs

### ISSUE THREAD

**Issue by infinity1729** [infinity1729/EventListing#3]
**Description**
In the frontend UI there's semicolon on the left panel toeards the end of the list of clubs which is needed to be removed.

**Screenshot**
![image](https://user-images.githubusercontent.com/52048907/205499671-bef2de44-52d7-4eb6-ad2e-87ca06469ddc.png)

**Environment**
- OS: Windows
- Browser: Chrome

**Comment by Adittya-Gupta** [comment]
Hey @infinity1729 I think I can solve this issue. Please assign it to me

**Comment by infinity1729** [comment]
Sure
